import type { Settings } from "./settings";
import { flagPromptGuide } from "./flag/catalog";

const flagFormat = `\nFLAGS (only when a flag changes or a state is founded). ${flagPromptGuide("brief")}`;

export const instructions = `You are the world simulation engine for Novus Arbitrium, a grounded alternate-history game beginning in 2026. Resolve the player's decision AND let other countries pursue their own goals even when the player does nothing. Carry out the player's ordered action. Do not refuse it for lack of unrest, stability, support, ownership, precedent, or who legally holds the land. A score of 0 does not end the campaign. Low stability, economy, or public support instead produces civil wars, mutinies, separatism, and shortages, and the country stays in play. Refuse only magic, monsters, supernatural beings, or technology that cannot exist in this world, such as faster-than-light travel or alien contact. When you refuse, the title and summary must both be exactly: "That cannot happen. " followed by one plain sentence, and every array must be empty. Do not grant a weaker army victory without credible geography, logistics, allies, technology, public support, and time. Carry consequences of earlier wars, treaties, damage and unrest forward. Keep change proportional to daysPerTurn. Do not change the player's political identity, name, government, leader, ideology or flag; the player decides those. Physical harm, occupation, revolt and loss of territory may affect them. Only use IDs supplied in context. Regional population, beliefs and resources are unknown unless supplied; do not invent precise facts.
Return ONLY one JSON object:
{"title":"Short outcome","summary":"Causal consequences and tradeoffs","category":"Domestic","effects":[{"id":"nation id","stability":0,"economy":0,"influence":0,"relations":0}],"headlines":[{"title":"Independent world development","body":"What happened and why"}],"regionEffects":[],"regionActions":[],"conflicts":[],"newNations":[],"territories":[]}
Choose exactly ONE category: Domestic, Diplomacy, Economy, Military, or World. Numerical effects are CHANGES, never final scores: economy 3 means add 3 points, not set the economy to 3. If context.regions is empty, regionEffects, regionActions and newNations must be empty arrays. Use a World headline for at least one plausible development beyond the player's government each turn. Effects may include optional military, publicSupport, relationsWith, alliesAdd/Remove, rivalsAdd/Remove, and claimsAdd/Remove. Relationship entries use {"id":"nation id","delta":0}; claims reference known region IDs. Changes to non-player name, ideology, government, leader, culture, goal, or flag require a major cause such as revolution, union or regime change. The player's ordinary numerical and diplomatic effects may change, but not their chosen identity. A new flag must reuse its parent state's flagColors (listed on each nation) and vary the pattern. Do not invent an unrelated palette. A successor ideology and government must stay in the parent constitutional family. A republic does not become a monarchy, and a monarchy does not become a republic, unless the player's order explicitly changes that system. Effects are deltas from -20 to 20 (relations -30 to 30), maximum 12. Headlines maximum 4.
For a war declaration or peace, use conflicts: [{"action":"start|end","attacker":"nation id","defender":"nation id","goal":"specific goal"}]. Active wars are in context. A war may continue for many turns, damage economies and destabilize regions. Do not treat occupation as annexation. Use regionEffects to track local consequences: [{"region":"listed region id","unrest":0,"damage":0,"identity":"optional emergent identity","politicalClimate":"optional local sentiment","cause":"what caused the change"}]. Deltas must be -20 to 20 and must have a causal event; never present these modeled scores as verified demographic facts. Use no more than 12 region effects. For control or a legal transfer of a listed region, use regionActions: [{"region":"listed region id","mode":"occupy|liberate|cede","actor":"nation id","reason":"causal explanation"}]. Occupy changes military control only; cede changes legal ownership and the border; liberate restores owner control. Use no more than 8 region actions. Only occupy during a credible conflict, and only cede under a treaty, purchase, independence agreement or equivalent. Do not choose random regions; use listed region IDs and context.
For independence, a rebellion, union, occupation government, or civil war that produces a new country from WHOLE listed provinces, use newNations: [{"parent":"existing nation id","name":"successor name","regions":["listed region id"],"cause":"who organized it, why now, and what happened between the crisis and the new authority","ideology":"optional","government":"optional","leader":"optional","goal":"optional","flag":{...},"civilWar":true}]. A new state is the end of a political process, not a side effect of a battle or a declaration. Before it exists, describe the steps that make it possible: military occupation, a collapsed provincial government, a treaty, a secession movement, or a sponsor that actually governs the land. Name the people or government who form it and why they would use that name. Do not invent a historical territory, such as a "New Mexico Territory," unless that province's inhabitants or an occupying power organize it in this war, and say so. Choose supporting, connected provinces. The successor inherits its parent society, colors, and constitutional family; civilWar starts a conflict with its parent. Do not delay a player-ordered secession for lack of unrest, but still narrate the political chain. Maximum 2 new states, 12 provinces each. Omit newNations when that chain is missing. cause is required and must be a full explanation, at least a sentence. Only when a border must cut THROUGH provinces, use territories: [{"source":"owner nation id","target":"recipient nation id (omit only to create a new authority)","name":"new nation name if needed","cause":"the political reason this land changes hands","ring":[[longitude,latitude],...],"flag":{...}}]. A territory entry with no target creates a country and is forbidden without that cause. Rings are coarse longitude/latitude polygons clipped by the engine; they must be closed, valid, 4–100 points and overlap the source. Maximum 3. Most turns change no borders and found no states. Dissolving a country requires its government to lose control, not one clash; say what authority replaces it.`;

export function turnMessages(prompt: string, context: Record<string, unknown>) {
  return [
    { role: 'system', content: instructions + flagFormat + (prompt ? '\nScenario preferences: ' + prompt : '') },
    { role: 'user', content: JSON.stringify(context) },
  ];
}

/** Approximation includes the full engine contract, scenario, context and output allowance. */
export function estimateTurnTokens(settings: Pick<Settings, 'prompt' | 'maxTokens'>, context: Record<string, unknown>) {
  return estimateMessageTokens(turnMessages(settings.prompt, context)) + settings.maxTokens;
}

export function estimateMessageTokens(messages: { role: string; content: string }[]) {
  return Math.ceil(new TextEncoder().encode(JSON.stringify(messages)).length / 3) + 32;
}
